import React from "react";
import Head from "next/head";

const Header = () => {
  return (
    <Head>
      <title>Pendaftaran PERAK</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/assets/logo.svg" />
    </Head>
  );
};

export default Header;
